In [1]:
[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

In [11]:
import numpy

In [12]:
arr1 = numpy.arange(27)

In [13]:
  n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [14]:
arr2 = arr1.reshape(3,9)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [16]:
arr3 = arr1.reshape(3,3,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
arr4 = numpy.asarray([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
arr4

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [20]:
arr5 = numpy.arange(3,3,3)
arr5

array([], dtype=int32)